name: My First workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Welcome message
      run: echo "My frist github action jpb"
    - name: List files
      run: ls
    - name: Read file
      run: cat README.md