name: Generate ASCII Artwork 2

on: 
  push


jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Action checkout
      uses: actions/checkout@v4

    - name: list the file
      run: ls -lart

    - name: executing shell script
      run: |
        chmod +x ascii-script.sh
        ./ascii-script.sh